command_list(push_ax,12)
command_list(push_bx,13)
command_list(push_cx,14)
command_list(push_dx,15)
command_list(push_ex,16)
command_list(push,11)

command_list(pop_ax,22)
command_list(pop_bx,23)
command_list(pop_cx,24)
command_list(pop_dx,25)
command_list(pop_ex,26)
command_list(pop,21)

command_list(add,31)
command_list(sub,32)
command_list(mul,33)
command_list(del,34)

command_list(ja,41)
command_list(jae,42)
command_list(jb,43)
command_list(jbe,44)
command_list(je,45)
command_list(jne,46)
command_list(jmp,47)

command_list(out,51)
command_list(end,52)